application: cvv-chat
version: master

runtime: go
api_version: go1

handlers:

- url: /site/
  static_dir: public/
  secure: always

- url: /.*
  script: _go_app
  secure: always

# - url: /.*
# 	/_ah/queue/go/delay

builtins: 
- default: on
- remote_api: off
